name: Shared Core CI

on:
  push:
    paths:
      - 'packages/shared-core/**'
      - '.github/workflows/shared-core.yml'
  pull_request:
    paths:
      - 'packages/shared-core/**'
      - '.github/workflows/shared-core.yml'

jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/shared-core
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint || echo "No lint script defined, skipping."

      - name: Test
        run: pnpm test || echo "No test script defined, skipping."

      - name: Build
        run: pnpm build 